---
# Per environment values which override defaults in sg-typescript-test/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: sg-typescript-test.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://sg-typescript-test.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: tmp-james-dev
